name: Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build for Android with Gradle
        run: ./gradlew aat-android:build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: aat-android
          path: aat-android/build/outputs/apk/*
          if-no-files-found: error
